version: 2
jobs:
  build:
    docker:
      - image: rama982/dokar:latest
    steps:
      - checkout
      - run: wget https://github.com/oxygenfox/build_docker/raw/master/build_docker.sh
      - run: bash build_docker.sh
      
